name: EOD Universe Build

on:
  # JST 09:00 は UTC 00:00
  schedule:
    - cron: '0 0 * * 1-5'   # 平日 09:00 JST
  workflow_dispatch:

jobs:
  eod:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
      # ※ 取得系で使う環境変数はステップごとに Secrets から渡します

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          pip install -r requirements.txt

      - name: Build & Package EOD report
        env:
          TIINGO_API_KEY: ${{ secrets.TIINGO_API_KEY }}
          ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
          ALPHA_DAILY_BUDGET: 24
          ALPHA_REFRESH_DAYS: 30
          EXTENDED_STALE_DAYS: 7
          WEEKEND_SKIP: "false"   # 日本の休日連動を外す要件に合わせて false
        run: |
          set -e
          python -m scripts.fetch_and_build --universe data/universe_2025-09.csv --outdir reports

          # 成果物を ZIP 化（既に zip がある場合はスキップ）
          cd reports
          if compgen -G "*.zip" > /dev/null; then
            echo "ZIP already exists:"
            ls -l *.zip
          else
            echo "No zip found. Creating us-eod-report.zip from current directory..."
            zip -r us-eod-report.zip .
          fi
          ls -l

      - name: Upload artifact (us-eod-report)
        uses: actions/upload-artifact@v4
        with:
          name: us-eod-report
          path: reports/us-eod-report.zip
          if-no-files-found: error
          retention-days: 7

      - name: Append summary (digest)
        if: always()
        run: |
          echo "## Artifacts" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Name: \`us-eod-report\`" >> $GITHUB_STEP_SUMMARY
          echo "- Path: \`reports/us-eod-report.zip\`" >> $GITHUB_STEP_SUMMARY
          if [ -f reports/us-eod-report.zip ]; then
            DIGEST=$(sha256sum reports/us-eod-report.zip | awk '{print $1}')
            SIZE=$(ls -lh reports/us-eod-report.zip | awk '{print $5}')
            echo "- Size: ${SIZE}" >> $GITHUB_STEP_SUMMARY
            echo "- SHA256: \`${DIGEST}\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "- *(zip not found at summarize step)*" >> $GITHUB_STEP_SUMMARY
          fi
