name: EOD Universe Build

on:
  schedule:
    - cron: '0 9 * * 1-5'   # 平日 18:00 JST
  workflow_dispatch:

jobs:
  eod:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Build & Zip
        run: |
          python -m scripts.fetch_and_build --universe data/universe_2025-09.csv --outdir reports
          cd reports
          zip -r bloomo-eod-zip.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bloomo-eod-zip
          path: reports/bloomo-eod-zip.zip
          if-no-files-found: error
          retention-days: 7

      - name: Install runtime deps for ChatGPT transfer
        if: always()
        run: |
          pip install --upgrade --quiet requests
          sudo apt-get update -y
          sudo apt-get install -y jq
          chmod +x scripts/send_to_chatgpt.py

      - name: Send ZIP to ChatGPT (OpenAI Assistants API)
        if: always()
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ASSISTANT_ID: ${{ secrets.OPENAI_ASSISTANT_ID }}
          OPENAI_THREAD_ID: ${{ secrets.OPENAI_THREAD_ID }}
          ZIP_GLOB: "reports/*.zip"
          MESSAGE_JA: "本日のEOD ZIPを添付します。ユニバースのファンダメンタル更新と注目銘柄抽出をお願いします。"
        run: |
          python scripts/send_to_chatgpt.py
